--- osbook_03/12/bootload/Makefile.orig   Sun Feb 28 23:23:47 2010
+++ osbook_03/12/bootload/Makefile        Mon Sep  6 23:51:33 2010
@@ -27,9 +27,10 @@
 CFLAGS = -Wall -mh -nostdinc -nostdlib -fno-builtin
 #CFLAGS += -mint32 # intを32ビットにすると掛算／割算ができなくなる
 CFLAGS += -I.
-#CFLAGS += -g
+CFLAGS += -g
 CFLAGS += -Os
 CFLAGS += -DKZLOAD
+CFLAGS += -DSIMULATOR
 
 LFLAGS = -static -T ld.scr -L.